# Environment Configuration
environment:
  num_scenarios: 200
  start_seed: 1000
  use_render: False
  image_observation: True
  stack_size: 4
  decision_repeat: 4

  sensors:
    main_camera: [RGBCamera, 200, 200]
    lidar: [Lidar]
      

vehicle_config:
 
  # This ensures the environment returns a complete observation dictionary.
  image_source: main_camera
  lidar:
    num_lasers: 240
    distance: 50
    
# Training Configuration
training:
  policy: "MultiInputPolicy"
  total_timesteps: 500000
  num_envs: 2
  log_dir: "./ppo_metadrive_logs/"
  model_save_path: "./models/ppo_metadrive_multi_modal.zip"

# Evaluation Configuration
evaluation:
  model_load_path: "./models/ppo_metadrive_multi_modal.zip"
  num_episodes: 10